name: Build y Push a Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./farmacia
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Build y push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./mi-proyecto-react
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
